-- Enable the UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create the analytics_events table
CREATE TABLE IF NOT EXISTS public.analytics_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    event_name TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id), -- Nullable, links to Supabase Auth if used
    anon_id TEXT NOT NULL, -- Long-term user identity (device level)
    session_id TEXT NOT NULL, -- Short-term session identity (browser session)
    product_type TEXT CHECK (product_type IN ('quick', 'deep')),
    step TEXT, -- 'checklist_q1', 'checkout', 'payment_success'
    metadata JSONB DEFAULT '{}'::jsonb
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

-- Policy: Allow ANONYMOUS/PUBLIC to INSERT events (for tracking)
-- We strictly limit this to INSERT only. No Updates/Deletes/Selects for public.
CREATE POLICY "Enable insert for everyone" ON public.analytics_events
    FOR INSERT
    WITH CHECK (true);

-- Policy: Allow SERVICE_ROLE (Admin) to do EVERYTHING
-- The Dashboard Server Component will use the Service Role or an Admin Authenticated client.
CREATE POLICY "Enable full access for service role" ON public.analytics_events
    FOR ALL
    USING (auth.role() = 'service_role');

-- Indices for Dashboard Performance
-- 1. Index for filtering by Event Name (e.g., "Count distinct users who 'checkout_started'")
CREATE INDEX idx_analytics_event_name ON public.analytics_events(event_name);

-- 2. Index for Product Type (Quick vs Deep segmentation)
CREATE INDEX idx_analytics_product_type ON public.analytics_events(product_type);

-- 3. Index for Time-based queries (e.g., "Last 24h", "Last 30 days")
CREATE INDEX idx_analytics_created_at ON public.analytics_events(created_at);

-- 4. Index for Funnel Analysis (Tracking a specific anon_id through steps)
CREATE INDEX idx_analytics_anon_id ON public.analytics_events(anon_id);

-- 5. Index for Session Analysis
CREATE INDEX idx_analytics_session_id ON public.analytics_events(session_id);
